// generate-sitemap.js
const fs = require('fs');
const path = require('path');

const BASE_URL = 'https://rentspace.co.ke';

// ---------- SITEMAP CONFIGURATION ----------
const staticPages = [
  { url: '/', priority: '1.0', changefreq: 'weekly' },
  { url: '/rentals.html', priority: '0.9', changefreq: 'daily' },
  { url: '/airbnb.html', priority: '0.9', changefreq: 'daily' },
  { url: '/movers.html', priority: '0.8', changefreq: 'weekly' },
  { url: '/blog.html', priority: '0.9', changefreq: 'daily' },
  { url: '/contact.html', priority: '0.7', changefreq: 'monthly' }
];

const dynamicDirs = [
  { dir: 'blog', urlPrefix: '/blog/', priority: '0.8', changefreq: 'weekly' },
  { dir: 'property', urlPrefix: '/property/', priority: '0.7', changefreq: 'weekly' },
  { dir: 'airbnb', urlPrefix: '/airbnb/', priority: '0.7', changefreq: 'weekly' }
];

// ---------- ROBOTS.TXT CONTENT ----------
const robotsTxtContent = `# robots.txt for RentSpace.co.ke
User-agent: *
Allow: /

# Sitemap location (auto‑generated by same script)
Sitemap: ${BASE_URL}/sitemap.xml

# Optional: block private/admin areas (uncomment if needed)
# Disallow: /admin/
# Disallow: /private/
# Disallow: /temp/

# Crawl delay (be gentle – optional)
# Crawl-delay: 1
`;

// ---------- HELPER: SCAN DIRECTORIES FOR HTML FILES ----------
// ---------- HELPER: SCAN DIRECTORIES FOR HTML FILES ----------
function getAllHtmlFiles(dirPath, relativeDir) {
  let results = [];
  const fullPath = path.join(__dirname, dirPath);
  if (!fs.existsSync(fullPath)) return results;

  const items = fs.readdirSync(fullPath, { withFileTypes: true });
  for (const item of items) {
    if (item.isDirectory()) {
      console.log(`Scanning directory: ${path.join(dirPath, item.name)}`); // Log directory paths
      results = results.concat(getAllHtmlFiles(path.join(dirPath, item.name), path.join(relativeDir, item.name)));
    } else if (item.isFile() && item.name.endsWith('.html')) {
      results.push({
        url: `/${relativeDir}/${item.name}`,
        lastmod: fs.statSync(path.join(fullPath, item.name)).mtime.toISOString().split('T')[0]
      });
    }
  }
  return results;
}

// ---------- GENERATE SITEMAP.XML ----------
function generateSitemap() {
  const sitemapItems = [];

  // Static pages
  staticPages.forEach(page => {
    sitemapItems.push({
      loc: BASE_URL + page.url,
      lastmod: new Date().toISOString().split('T')[0],
      changefreq: page.changefreq,
      priority: page.priority
    });
  });

  // Dynamic pages from scanned directories
  dynamicDirs.forEach(({ dir, priority, changefreq }) => {
    const files = getAllHtmlFiles(dir, dir);
    files.forEach(file => {
      let urlPath = file.url;
      if (!urlPath.startsWith('/')) urlPath = '/' + urlPath;
      sitemapItems.push({
        loc: BASE_URL + urlPath,
        lastmod: file.lastmod,
        changefreq: changefreq,
        priority: priority
      });
    });
  });

  // Build XML
  const xmlHeader = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n';
  const xmlFooter = '</urlset>';
  const xmlUrls = sitemapItems.map(item => {
    return `  <url>
    <loc>${item.loc}</loc>
    <lastmod>${item.lastmod}</lastmod>
    <changefreq>${item.changefreq}</changefreq>
    <priority>${item.priority}</priority>
  </url>`;
  }).join('\n');

  const sitemap = xmlHeader + xmlUrls + '\n' + xmlFooter;

  fs.writeFileSync(path.join(__dirname, 'sitemap.xml'), sitemap);
  console.log(`✅ Sitemap generated with ${sitemapItems.length} URLs`);
}

// ---------- GENERATE ROBOTS.TXT ----------
function generateRobotsTxt() {
  fs.writeFileSync(path.join(__dirname, 'robots.txt'), robotsTxtContent);
  console.log('✅ robots.txt generated');
}

// ---------- RUN BOTH ----------
function generateAll() {
  generateSitemap();
  generateRobotsTxt();
  console.log('\n🎉 Both sitemap.xml and robots.txt are ready for upload to your website root.');
}

generateAll();